[WIP] "I prefer to think that God is not dead, just drunk" 		-- John Huston

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -34,8 +34,30 @@ on:
     # tags:
     #   - "v*.*.*" # on every version tag will build a new android artifact.
     # branches-ignore: [ poc/**]
+    paths-ignore:
+      - 'docs/**'
+      - 'README.md'
+      - 'LICENSE'
+      - 'CONTRIBUTING.md'
+      - 'CODE_OF_CONDUCT.md'
+      - 'AUTHORS'
   pull_request:
-    branches: [ develop ]
+    branches: [ develop, releases/v* ]
+    paths-ignore:
+      - 'docs/**'
+      - 'README.md'
+      - 'LICENSE'
+      - 'CONTRIBUTING.md'
+      - 'CODE_OF_CONDUCT.md'
+      - 'AUTHORS'
+  workflow_dispatch:
+    paths-ignore:
+      - 'docs/**'
+      - 'README.md'
+      - 'LICENSE'
+      - 'CONTRIBUTING.md'
+      - 'CODE_OF_CONDUCT.md'
+      - 'AUTHORS'
 
   schedule:
     - cron: '30 23 * * TUE'
@@ -51,117 +73,171 @@ env:
   REGISTRY: docker.io
   # IMAGE_NAME: ${{ github.repository }}
   IMAGE_NAME: doevelopper/cfs-dev-tools-common:latest
+  buildDir: '${{ github.workspace }}/build'
 
 jobs:
-  gcc-build-end-2-end:
+  end-2-end:
     name: Bazel Test All (opt) usinh GCC
     timeout-minutes: 60
-    runs-on: ubuntu-latest
+    runs-on: ${{ matrix.os }}
+    continue-on-error: ${{ matrix.ignore-errors }}
     # container: doevelopper/cfs-dev-tools-common:latest
     strategy:
       fail-fast: false
       matrix:
-        arch: ["Win32", "x64", "ARM64"]
+        # arch: ["Win64", "x64", "ARM64"]
+        # target: [ linux-x64, linux-armv8-64]
+        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
+        build_type: ["Debug", "Release"]
+        lib_type: ["static", "shared"]
+        include:
+          - os: ubuntu-latest
+            compiler: clang
+            compiler-version: 11
+            ignore-errors: false
+            # This compiler is supported only on a best-effort basis
+            ignore-errors: true
+          - os: ubuntu-latest
+            compiler: gcc
+            compiler-version: 10
+            ignore-errors: false
+
+    name: Build and test ${{ matrix.os_name }} ${{ matrix.build_type }} ${{ matrix.lib_type }}
+    runs-on: ${{ matrix.os }}
+
     steps:
-      - uses: actions/checkout@v2
-      # - name: set up JDK 1.8
-      #   uses: actions/setup-java@v1
+
+      - name: Configure git to preserve line endings
+        # Otherwise, tests fail on Windows because "golden" test outputs will not
+        # have the correct line endings.
+        run: git config --global core.autocrlf false
+
+      # - uses: actions/checkout@v2
+      # # - name: set up JDK 1.8
+      # #   uses: actions/setup-java@v1
+      # #   with:
+      # #     java-version: 1.8
+      # - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+      # - run: echo "🖥️ The workflow is now ready to test your code on the runner."
+      # - name: List files in the repository
+      #   run: |
+      #     ls ${{ github.workspace }}
+
+      # - name: Mount Bazel Cache
+      #   uses: actions/cache@v1
       #   with:
-      #     java-version: 1.8
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
+      #     path: "~/.cache/bazel"
+      #     key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE') }}
+      #     restore-keys: ${{ runner.os }}-bazel
 
-      - name: Mount Bazel Cache
-        uses: actions/cache@v1
-        with:
-          path: "~/.cache/bazel"
-          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE') }}
-          restore-keys: ${{ runner.os }}-bazel
+      # - name: Install bazelisk
+      #   run: |
+      #     curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
+      #     mkdir -p "${GITHUB_WORKSPACE}/bin/"
+      #     mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
+      #     chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
 
-      - name: Install bazelisk
-        run: |
-          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
-          mkdir -p "${GITHUB_WORKSPACE}/bin/"
-          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
-          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
+      # # - name: Install dependencies via apt
+      # #   run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
+      # - name: Install/configure Clang compiler toolchain
+      #   if: matrix.compiler == 'clang'
+      #   run: |
+      #     sudo apt-get install -qy clang-${{matrix.compiler-version}}
+      #     echo "CXX=clang++-${{matrix.compiler-version}}" >> $GITHUB_ENV
+      #     echo "CC=clang-${{matrix.compiler-version}}" >> $GITHUB_ENV
 
-      # - name: Install dependencies via apt
-      #   run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
+      # - name: Install/configure GCC compiler toolchain
+      #   if: matrix.compiler == 'gcc'
+      #   run: |
+      #     sudo apt-get install -qy g++-${{matrix.compiler-version}}
+      #     echo "CXX=g++-${{matrix.compiler-version}}" >> $GITHUB_ENV
+      #     echo "CC=gcc-${{matrix.compiler-version}}" >> $GITHUB_ENV
 
-      - name: Build
-        run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" build --nobuild //...
+      # - name: Get specific version CMake, v3.21.1
+      #   uses: lukka/get-cmake@v3.21.1
 
-      - name: Unit Test
-        run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" test --nobuild //...
+      # - name: Build
+      #   run: |
+      #     "${GITHUB_WORKSPACE}/bin/bazel" build --nobuild //...
+
+      # - name: Unit Test
+      #   run: |
+      #     "${GITHUB_WORKSPACE}/bin/bazel" test --nobuild //...
 
       # - name: Bazel Test Target (opt)
       #   run: |
       #     "${GITHUB_WORKSPACE}/bin/bazel" test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
 
-      # - uses: actions/upload-artifact@v1.0.0
+      # - uses: actions/upload-artifact@v1.0.0  #actions/upload-artifact@v2
       #   with:
       #     name: filament-linux
-      #     path: out/filament-release-linux.tgz
+      #     path: out/${{ github.repository }}.${{ runner.os }}.tar.gz
+
+      # - name: Archive results
+      #   if: ${{ success() || failure() }}
+      #   uses: actions/upload-artifact@v2
+      #   with:
+      #     name: ${{ github.repository }}.${{ runner.os }}-${{ matrix.target }}
+      #     path: |
+      #       report.html
+      #       log.html
+      #       robot_output.xml
+      #       snapshots
 
       - run: echo "🍏 This job's status is ${{ job.status }}."
 
-  clang-build-end-2-end:
-    name: Bazel Test All (opt) usinh CLANG
-    timeout-minutes: 60
-    # container: doevelopper/cfs-dev-tools-common:latest
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
-      # - name: set up JDK 1.8
-      #   uses: actions/setup-java@v1
-      #   with:
-      #     java-version: 1.8
-      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
-      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
+  # clang-build-end-2-end:
+  #   name: Bazel Test All (opt) usinh CLANG
+  #   timeout-minutes: 60
+  #   # container: doevelopper/cfs-dev-tools-common:latest
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     # - name: set up JDK 1.8
+  #     #   uses: actions/setup-java@v1
+  #     #   with:
+  #     #     java-version: 1.8
+  #     - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
+  #     - run: echo "🖥️ The workflow is now ready to test your code on the runner."
+  #     - name: List files in the repository
+  #       run: |
+  #         ls ${{ github.workspace }}
 
-      - name: Mount Bazel Cache
-        uses: actions/cache@v1
-        with:
-          path: "~/.cache/bazel"
-          key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE') }}
-          restore-keys: ${{ runner.os }}-bazel
+  #     - name: Mount Bazel Cache
+  #       uses: actions/cache@v1
+  #       with:
+  #         path: "~/.cache/bazel"
+  #         key: ${{ runner.os }}-bazel-${{ hashFiles('WORKSPACE') }}
+  #         restore-keys: ${{ runner.os }}-bazel
 
-      - name: Install bazelisk
-        run: |
-          curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
-          mkdir -p "${GITHUB_WORKSPACE}/bin/"
-          mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
-          chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
+  #     - name: Install bazelisk
+  #       run: |
+  #         curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/v1.10.1/bazelisk-linux-amd64"
+  #         mkdir -p "${GITHUB_WORKSPACE}/bin/"
+  #         mv bazelisk-linux-amd64 "${GITHUB_WORKSPACE}/bin/bazel"
+  #         chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
 
-      # - name: Install dependencies via apt
-      #   run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
+  #     # - name: Install dependencies via apt
+  #     #   run: sudo apt-get install python3-dev python3-distutils python3-dev python-is-python3 libtinfo5
 
-      - name: Build
-        run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" build --nobuild //...
+  #     - name: Build
+  #       run: |
+  #         "${GITHUB_WORKSPACE}/bin/bazel" build --nobuild //...
 
-      - name: Unit Test
-        run: |
-          "${GITHUB_WORKSPACE}/bin/bazel" test --nobuild //...
+  #     - name: Unit Test
+  #       run: |
+  #         "${GITHUB_WORKSPACE}/bin/bazel" test --nobuild //...
 
-      # - name: Bazel Test Target (opt)
-      #   run: |
-      #     "${GITHUB_WORKSPACE}/bin/bazel" test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
+  #     # - name: Bazel Test Target (opt)
+  #     #   run: |
+  #     #     "${GITHUB_WORKSPACE}/bin/bazel" test -c opt --test_output=all --runs_per_test=$BAZEL_RUNS_PER_TEST -- $BAZEL_TARGET
 
-      # - uses: actions/upload-artifact@v1.0.0
-      #   with:
-      #     name: filament-linux
-      #     path: out/filament-release-linux.tgz
+  #     # - uses: actions/upload-artifact@v1.0.0
+  #     #   with:
+  #     #     name: filament-linux
+  #     #     path: out/filament-release-linux.tgz
 
-      - run: echo "🍏 This job's status is ${{ job.status }}."
+  #     - run: echo "🍏 This job's status is ${{ job.status }}."
 
 
   # Explore-GitHub-Actions:
@@ -189,7 +265,7 @@ jobs:
   # clang-compile-test:
   #   needs: clang-compile
 
-  # clang-format-style:
+
   # clang-cppcheck-analyzer:
   # clang-clang-tidy-analyzer:
 
@@ -212,3 +288,14 @@ jobs:
 
   # Deploy:
   #   runs-on: doevelopper/cfs-dev-tools-common:latest
+  # clang-format-style:
+  # runs-on: ubuntu-latest
+  # steps:
+  #   - name: Checkout code
+  #     uses: actions/checkout@v2
+  #     with:
+  #       path: src
+  #        ref: ${{ github.event.inputs.ref || github.ref }}
+  #        fetch-depth: 2
+  #   # - name: Apply style
+  #   #   ls ${{ github.workspace }}
